image: node:12

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules

before_script:
  - npm i

testing: 
  stage: test
  script: 
    - npm run test:once
  except: 
    - master

deploying: 
  stage: deploy
  script: 
    - npm run build
    # add steps needed to deploy the api 
  when:
    on_success
  only:
    - master
