version: '3.7'

services:
  react: 
    image: react
    build: 
      context: .
      dockerfile: dockerfile
    ports: 
      - 3000:3000 
    container_name: react
    volumes: 
      - ./src/app/src
    restart: always
