version: '3.7'

services:
  react: 
    image: react
    build:
      context: ../
      dockerfile: docker/dev.dockerfile
    ports: 
      - 3000:3000 
    container_name: react
    environment: 
      - REACT_APP_API_URL: some-url
    volumes:
      - ../:/app
    restart: always
